### ISSUE TITLE
Fails to install with pip

### ISSUE THREAD

**Issue by jmtaysom** [LuminosoInsight/python-ftfy#108]
When I try to install ftfy it errors out as follows

```
$ pip3 install ftfy
Obtaining file:///Users/jt/workspace/ftfy/python-ftfy
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748) -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/jt/workspace/ftfy/python-ftfy/setup.py", line 62, in <module>
        'Documentation': 'http://ftfy.readthedocs.io',
      File "/Users/jt/Library/Python/3.6/lib/python/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/Users/jt/Library/Python/3.6/lib/python/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/jt/Library/Python/3.6/lib/python/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/jt/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 770, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/jt/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 1053, in best_match
        return self.obtain(req, installer)
      File "/Users/jt/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 1065, in obtain
        return installer(requirement)
      File "/Users/jt/Library/Python/3.6/lib/python/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/jt/Library/Python/3.6/lib/python/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/jt/workspace/ftfy/python-ftfy/
```

I am able to `pip install 'ftfy<5` without any issue. I can successfully install it if I first manually install pytest-runner. I believe the issue is related to https://stackoverflow.com/questions/27307082/install-package-which-has-setup-requires-from-local-source-distributions/27789623#27789623

https://github.com/pytest-dev/pytest-runner#conditional-requirement adding the suggested code from here makes it so that the install works fine however the tests still dont work without first manually installing pytest and pytest-runner. This could be handled with an extra requires section.

**Comment by rspeer** [comment]
Thanks for pointing this out. pytest-runner seemed like a natural thing to include when we upgraded from nose to pytest, but it seems to cause too many problems by adding additional complexity at install time. So let's not use it.
