### ISSUE TITLE
Undeclared dependency on setuptools

### ISSUE THREAD

**Issue by lilyball** [LuminosoInsight/python-ftfy#150]
This package appears to have an undeclared dependency on `setuptools`. This may not affect most setups but it does affect someone loading this package via Nix.

Example:

```
$ nix run '(with import <nixpkgs> {}; python3.withPackages (pkgs: [ pkgs.ftfy ]))' -c python3
Python 3.7.6 (default, Mar 11 2020, 12:53:39) 
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ftfy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/yss5qkwzvh8cgiz5fawf5mhjvj6cmvn8-python3-3.7.6-env/lib/python3.7/site-packages/ftfy/__init__.py", line 11, in <module>
    from ftfy import fixes
  File "/nix/store/yss5qkwzvh8cgiz5fawf5mhjvj6cmvn8-python3-3.7.6-env/lib/python3.7/site-packages/ftfy/fixes.py", line 11, in <module>
    from ftfy.badness import text_cost
  File "/nix/store/yss5qkwzvh8cgiz5fawf5mhjvj6cmvn8-python3-3.7.6-env/lib/python3.7/site-packages/ftfy/badness.py", line 9, in <module>
    from ftfy.chardata import chars_to_classes
  File "/nix/store/yss5qkwzvh8cgiz5fawf5mhjvj6cmvn8-python3-3.7.6-env/lib/python3.7/site-packages/ftfy/chardata.py", line 12, in <module>
    from pkg_resources import resource_string
ModuleNotFoundError: No module named 'pkg_resources'
```

Using `nix run '(with import <nixpkgs> {}; python3.withPackages (pkgs: [ pkgs.ftfy pkgs.setuptools ]))' -c python3` instead works.

**Comment by rspeer** [comment]
Thanks Lily -- I hadn't previously known about how Nix manages Python packages, or that setuptools could install a package into an environment where setuptools itself is unavailable.

This made me think that it's as good a time as any to just remove the use of `pkg_resources`, so my proposed solution is in #152.

**Comment by rspeer** [comment]
This is fixed by now.
