### ISSUE TITLE
What happened with fix_entities?

### ISSUE THREAD

**Issue by ZJaume** [LuminosoInsight/python-ftfy#176]
Using `fix_entities` keyword argument gives:
```
>>> ftfy.fix_text("&amp;\n<html>\n&amp;", fix_entities=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.conda/envs/new/lib/python3.7/site-packages/ftfy/__init__.py", line 279, in fix_text
    config = config._replace(**kwargs)
  File "/home/user/.conda/envs/new/lib/python3.7/collections/__init__.py", line 416, in _replace
    raise ValueError(f'Got unexpected field names: {list(kwds)!r}'
ValueError: Got unexpected field names: ['fix_entities']
```
but the parameter still appears in the [documentation](https://ftfy.readthedocs.io/en/latest/config.html).

**Comment by illestvillain** [comment]
From the code, it seems that **unescape_html** is full equivalent and **fix_entities** was dropped as an inconsistency

**Comment by rspeer** [comment]
The `fix_entities` parameter is restored, with a DeprecationWarning, in 6.0.3.
