### ISSUE TITLE
PyPy: import failure

### ISSUE THREAD

**Issue by tptee** [LuminosoInsight/python-ftfy#35]
Hi there,

I get the following error when trying to import ftfy into a PyPy console:

```
Python 2.7.8 (10f1b29a2bd21f837090286174a9ca030b8680b2, Feb 05 2015, 17:51:14)
[PyPy 2.5.0 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import ftfy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/pypy/2.5.0/libexec/site-packages/ftfy/__init__.py", line 15, in <module>
    from ftfy import fixes
  File "/usr/local/Cellar/pypy/2.5.0/libexec/site-packages/ftfy/fixes.py", line 8, in <module>
    from ftfy.chardata import (possible_encoding,
  File "/usr/local/Cellar/pypy/2.5.0/libexec/site-packages/ftfy/chardata.py", line 45, in <module>
    ENCODING_REGEXES = _build_regexes()
  File "/usr/local/Cellar/pypy/2.5.0/libexec/site-packages/ftfy/chardata.py", line 36, in _build_regexes
    charlist = latin1table.encode('latin-1').decode(encoding)
  File "/usr/local/Cellar/pypy/2.5.0/libexec/site-packages/ftfy/bad_codecs/__init__.py", line 72, in search_function
    from ftfy.bad_codecs.sloppy import CODECS
  File "/usr/local/Cellar/pypy/2.5.0/libexec/site-packages/ftfy/bad_codecs/sloppy.py", line 156, in <module>
    CODECS[_new_name] = make_sloppy_codec(_encoding)
  File "/usr/local/Cellar/pypy/2.5.0/libexec/site-packages/ftfy/bad_codecs/sloppy.py", line 97, in make_sloppy_codec
    decoded_chars = all_bytes.decode(encoding, errors='replace')
  File "/usr/local/Cellar/pypy/2.5.0/libexec/lib-python/2.7/encodings/cp1250.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
TypeError: expected string, got bytearray object
```

Any ideas?

**Comment by rspeer** [comment]
This appears to be a bug in pypy's standard library. The `codecs.charmap_decode` method requires that its argument is a string in pypy, but `bytearray.decode` calls it with a bytearray.

On 2.7:

    >>> bytearray(b'test').decode('cp1250')
    u'test'

On PyPy 2.5.0:

    >>>> bytearray('test').decode('cp1250')                                                                                                                                                                                                
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/rspeer/src/pypy-2.5.0-linux64/lib-python/2.7/encodings/cp1250.py", line 15, in decode
        return codecs.charmap_decode(input,errors,decoding_table)
    TypeError: expected string, got bytearray object

It works on PyPy3, however.

**Comment by rspeer** [comment]
Reported to PyPy: https://bitbucket.org/pypy/pypy/issue/2007/pypy2-codecscharmap_decode-doesnt-work-on

**Comment by tptee** [comment]
Awesome, thanks for reporting it!
