### ISSUE TITLE
AttributeError: module 'ftfy' has no attribute 'bad_codecs'

### ISSUE THREAD

**Issue by omelnikov** [LuminosoInsight/python-ftfy#92]
Looks like a very useful tool. Installed version 5.2.0 on Python 3.6 from Anaconda3 on Windows 10 Pro x64. When trying to import the following error comes up. Any thoughts?
The import fails in PyCharm, but succeeds in Python prompt window.

```
import ftfy
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-2a60fe17c2b6>", line 1, in <module>
    import ftfy
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ftfy\__init__.py", line 17, in <module>
    ftfy.bad_codecs.ok()
AttributeError: module 'ftfy' has no attribute 'bad_codecs'
```

**Comment by rspeer** [comment]
That's weird. To me, it sounds like a bug with Anaconda's packaging of ftfy.

Does your `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ftfy\` directory contain a `bad_codecs` subdirectory, including `bad_codecs\__init__.py`?

And does the main `__init__.py`, a directory above that, contain the line:

    __version__ == '5.2.0'

**Comment by omelnikov** [comment]
Yes to both questions. The sub-folders are listed below, the `__init__.py` from the parent folder is attached.

```
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Lib\site-packages\ftfy\bad_codecs>dir /s
 Volume in drive C has no label.
 Volume Serial Number is AECD-79D0

 Directory of C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Lib\site-packages\ftfy\bad_codecs

01/25/2018  09:31 PM    <DIR>          .
01/25/2018  09:31 PM    <DIR>          ..
01/25/2018  09:31 PM             6,560 sloppy.py
01/25/2018  09:31 PM             9,573 utf8_variants.py
01/25/2018  09:31 PM             3,137 __init__.py
01/25/2018  09:31 PM    <DIR>          __pycache__
               3 File(s)         19,270 bytes

 Directory of C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Lib\site-packages\ftfy\bad_codecs\__pycache__

01/25/2018  09:31 PM    <DIR>          .
01/25/2018  09:31 PM    <DIR>          ..
01/25/2018  09:31 PM             6,692 sloppy.cpython-36.pyc
01/25/2018  09:31 PM             6,476 utf8_variants.cpython-36.pyc
01/25/2018  09:31 PM             3,181 __init__.cpython-36.pyc
               3 File(s)         16,349 bytes

     Total Files Listed:
               6 File(s)         35,619 bytes
               5 Dir(s)  748,511,277,056 bytes free
```

**Comment by omelnikov** [comment]
I worked around it by creating a Python virtual environment with inherited global site-packages. Now the import seems to load properly.
